# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-11 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='album/%Y/%m', verbose_name='照片')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('tag', models.CharField(max_length=20, verbose_name='标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
    ]
