# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-11 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': '相册', 'verbose_name_plural': '相册'},
        ),
    ]
