# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-12 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180711_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='', max_length=14, verbose_name='照片名'),
        ),
    ]
