# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-13 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_album_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
