# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-19 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_album_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='writer',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
