# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='数据ID')),
                ('fav_type', models.IntegerField(choices=[(1, '照片'), (2, '文章')], default=1, verbose_name='收藏类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '展示内容',
                'verbose_name_plural': '展示内容',
            },
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'verbose_name': '用户留言', 'verbose_name_plural': '用户留言'},
        ),
    ]
