# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180717_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usershow',
            old_name='fav_id',
            new_name='show_id',
        ),
        migrations.RenameField(
            model_name='usershow',
            old_name='fav_type',
            new_name='show_type',
        ),
    ]
