# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-12 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_show',
            field=models.CharField(default='', max_length=150, verbose_name='展示内容'),
        ),
    ]
